name: Deploy Laravel to Oracle VPS

on:
    push:
        branches: [main]
        paths:
        - 'backend/**'
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      cd /var/www/Portfolio/backend
                      php artisan down
                      git pull origin main
                      composer install --no-interaction --prefer-dist --optimize-autoloader
                      php artisan migrate --force
                      php artisan config:cache
                      php artisan route:cache
                      php artisan view:cache
                      php artisan up
